export type PackageStatus = 'reference' | 'migrate' | 'audit' | 'repair' | 'scaffold' | 'historical'

export interface PackageCatalogEntry {
  repo: string
  pkg: string | null
  status: PackageStatus
  category: string
  runtime: string[]
  summary: string
  flow: [string, string, string]
  example: string
}

export const packageCatalog: PackageCatalogEntry[] = [
  {
    repo: 'graphql-api',
    pkg: null,
    status: 'reference',
    category: 'core',
    runtime: ['node', 'browser'],
    summary: 'Modern core workspace, docs, shared release policy and migration control plane.',
    flow: ['repositories', 'GraphQL API', 'packages'],
    example: 'query { packageCatalog { repository status runtime } }',
  },
  {
    repo: 'apollo-datasource-ftp',
    pkg: '@graphql-api/apollo-datasource-ftp',
    status: 'historical',
    category: 'filesystem',
    runtime: ['node'],
    summary:
      'Historical Apollo datasource seed for FTP; extract remote-filesystem behavior before retiring Apollo-specific glue.',
    flow: ['FTP', 'GraphQL', 'files'],
    example: 'query { remoteFiles(path: "/") { name size } }',
  },
  {
    repo: 'graphql-iso-textile',
    pkg: '@graphql-api/textile',
    status: 'migrate',
    category: 'storage',
    runtime: ['node'],
    summary:
      'Textile integration seed for content-addressed storage; validate current Textile ecosystem before migration.',
    flow: ['Textile', 'GraphQL', 'content'],
    example: 'query { textileBuckets { key name } }',
  },
  {
    repo: 'graphql-api-stripe',
    pkg: '@graphql-api/stripe',
    status: 'audit',
    category: 'api',
    runtime: ['node', 'edge'],
    summary: 'Stripe wrapper requiring a current SDK/API/schema audit before revival.',
    flow: ['Stripe', 'GraphQL', 'billing'],
    example: 'query { stripeCustomer(id: "cus_…") { id email } }',
  },
  {
    repo: 'graphql-local-file-system-access',
    pkg: '@graphql-local/file-system-access',
    status: 'reference',
    category: 'filesystem',
    runtime: ['browser'],
    summary:
      'Browser-local File System Access reference package and natural snapshot input adapter.',
    flow: ['local files', 'GraphQL', 'browser'],
    example: 'query { files(path: "/") { name kind } }',
  },
  {
    repo: 'graphql-api-vercel',
    pkg: '@graphql-api/vercel',
    status: 'audit',
    category: 'runtime',
    runtime: ['node', 'edge'],
    summary:
      'Vercel integration seed; redefine around current deployment/runtime APIs before publishing.',
    flow: ['Vercel', 'GraphQL', 'deployments'],
    example: 'query { deployment(id: "dpl_…") { id state url } }',
  },
  {
    repo: 'graphql-api-template',
    pkg: '@graphql-api/template',
    status: 'historical',
    category: 'template',
    runtime: ['node'],
    summary: 'Older TypeScript 4 / Codegen 2 template superseded by the modern core workspace.',
    flow: ['template', 'GraphQL', 'package'],
    example: 'query { packageTemplate { runtime capabilities } }',
  },
  {
    repo: 'graphql-api-netlify',
    pkg: '@graphql-api/netlify',
    status: 'audit',
    category: 'runtime',
    runtime: ['node', 'edge'],
    summary: 'Netlify integration seed; validate current APIs and narrow the supported surface.',
    flow: ['Netlify', 'GraphQL', 'deployments'],
    example: 'query { deployment(id: "…") { id state url } }',
  },
  {
    repo: 'graphql-local-textile',
    pkg: '@graphql-local/textile',
    status: 'migrate',
    category: 'storage',
    runtime: ['browser', 'node'],
    summary:
      'Local Textile/storage experiment that can feed the modern content-addressed adapter layer.',
    flow: ['local data', 'GraphQL', 'Textile'],
    example: 'mutation { storeText(text: "hello") { cid } }',
  },
  {
    repo: 'graphql-api-rossum',
    pkg: '@graphql-api/rossum',
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'Document-processing wrapper; current Rossum API/auth/pagination must be verified first.',
    flow: ['Rossum', 'GraphQL', 'documents'],
    example: 'query { rossumAnnotation(id: "…") { id status } }',
  },
  {
    repo: 'graphql-api-sevdesk',
    pkg: null,
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'Sevdesk repository without a verified modern root package; inspect upstream API and repository contents.',
    flow: ['sevdesk', 'GraphQL', 'accounting'],
    example: 'query { invoices { id status } }',
  },
  {
    repo: 'graphql-api-debitoor',
    pkg: null,
    status: 'scaffold',
    category: 'api',
    runtime: ['node'],
    summary: 'Empty/scaffold repository; keep catalogued but do not imply a supported package.',
    flow: ['Debitoor', 'GraphQL', 'archive'],
    example: 'query { repository(name: "graphql-api-debitoor") { status } }',
  },
  {
    repo: 'graphql-api-etsy',
    pkg: null,
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'Etsy wrapper candidate without verified package metadata; needs current API/auth validation.',
    flow: ['Etsy', 'GraphQL', 'commerce'],
    example: 'query { etsyListing(id: "…") { id title } }',
  },
  {
    repo: 'graphql-schema',
    pkg: null,
    status: 'scaffold',
    category: 'tooling',
    runtime: ['node'],
    summary:
      'Schema repository without a verified root package; candidate for shared schema artifacts or archival.',
    flow: ['SDL', 'GraphQL', 'artifacts'],
    example: 'query { schemas { name revision } }',
  },
  {
    repo: 'graphql-iso-space-storage',
    pkg: '@graphql-local/space-storage',
    status: 'migrate',
    category: 'storage',
    runtime: ['browser', 'node'],
    summary: 'Storage abstraction seed that can be aligned with IPLD/CAR and provider adapters.',
    flow: ['space storage', 'GraphQL', 'content'],
    example: 'mutation { putObject(input: { key: "note", text: "hello" }) { id } }',
  },
  {
    repo: 'graphql-api-magic',
    pkg: null,
    status: 'audit',
    category: 'identity',
    runtime: ['browser', 'node'],
    summary: 'Magic identity integration candidate; verify current SDK and authentication model.',
    flow: ['Magic', 'GraphQL', 'identity'],
    example: 'query { identity(address: "0x…") { id } }',
  },
  {
    repo: 'apollo-link-worker',
    pkg: '@graphql-local/apollo-link-worker',
    status: 'historical',
    category: 'runtime',
    runtime: ['worker'],
    summary:
      'Historical Worker link; extract Request/Response/stream semantics into provider-neutral worker packages.',
    flow: ['GraphQL op', 'Worker', 'response'],
    example: 'mutation { dispatchWorker(input: { method: "run" }) { id state } }',
  },
  {
    repo: 'graphql-api-pinata',
    pkg: '@graphql-api/pinata',
    status: 'migrate',
    category: 'storage',
    runtime: ['node', 'edge'],
    summary: 'Pinata seed for an IPFS pinning-provider adapter behind a common content interface.',
    flow: ['CID', 'GraphQL', 'Pinata'],
    example: 'mutation { pin(cid: "bafy…") { id status } }',
  },
  {
    repo: 'graphql-api-infura',
    pkg: '@graphql-api/infura',
    status: 'migrate',
    category: 'storage',
    runtime: ['node', 'edge'],
    summary: 'Infura seed; separate provider details from shared content-addressed contracts.',
    flow: ['CID/RPC', 'GraphQL', 'Infura'],
    example: 'query { content(cid: "bafy…") { cid size } }',
  },
  {
    repo: 'graphql-api-nft-storage',
    pkg: '@graphql-api/nft-storage',
    status: 'migrate',
    category: 'storage',
    runtime: ['node', 'edge'],
    summary:
      'NFT.Storage seed; validate current service lifecycle and reuse as a storage-provider adapter if applicable.',
    flow: ['files', 'GraphQL', 'NFT.Storage'],
    example: 'mutation { storeArtifact(input: { name: "artifact.car" }) { cid } }',
  },
  {
    repo: 'exspiration',
    pkg: null,
    status: 'scaffold',
    category: 'tooling',
    runtime: ['node'],
    summary: 'Experimental repository without a verified package surface; classify before reuse.',
    flow: ['experiment', 'GraphQL', 'decision'],
    example: 'query { repository(name: "exspiration") { status } }',
  },
  {
    repo: 'graphql-local-ipfs',
    pkg: '@graphql-local/ipfs',
    status: 'migrate',
    category: 'p2p',
    runtime: ['browser', 'node'],
    summary:
      'Primary IPFS seed; modernize on Helia and expose CID/IPLD helpers instead of discontinued js-ipfs assumptions.',
    flow: ['bytes', 'Helia/IPFS', 'CID'],
    example: 'mutation { addText(text: "hello") { cid } }',
  },
  {
    repo: 'graphql-api-components-ai',
    pkg: '@graphql-api/components-ai',
    status: 'audit',
    category: 'ai',
    runtime: ['browser', 'node'],
    summary:
      'Components AI wrapper; verify the upstream product/API and decide whether a narrow schema remains useful.',
    flow: ['Components AI', 'GraphQL', 'component'],
    example: 'query { component(id: "…") { id name } }',
  },
  {
    repo: 'graphql-api-youtube',
    pkg: '@graphql-api/youtube',
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'YouTube wrapper with an old googleapis dependency; validate scopes, quotas and current supported surface.',
    flow: ['YouTube', 'GraphQL', 'video'],
    example: 'query { youtubeVideo(id: "…") { id title } }',
  },
  {
    repo: 'graphql-module-template',
    pkg: null,
    status: 'historical',
    category: 'template',
    runtime: ['node'],
    summary:
      'Historical module-template repository; supersede with the modern package contract/template.',
    flow: ['template', 'GraphQL', 'module'],
    example: 'query { packageTemplate { status } }',
  },
  {
    repo: 'graphql-api-symbl',
    pkg: '@graphql-api/symbl',
    status: 'audit',
    category: 'ai',
    runtime: ['node'],
    summary:
      'Symbl integration seed; verify the current upstream service lifecycle and API before migration.',
    flow: ['conversation', 'GraphQL', 'insights'],
    example: 'query { conversation(id: "…") { id status } }',
  },
  {
    repo: 'graphql-api-notion',
    pkg: '@graphql-api/notion',
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'Notion wrapper uses a very old client; rewrite against the current Notion API/client if retained.',
    flow: ['Notion', 'GraphQL', 'page'],
    example: 'query { notionPage(id: "…") { id title } }',
  },
  {
    repo: 'graphql-api-sftp',
    pkg: '@graphql-api/sftp',
    status: 'migrate',
    category: 'filesystem',
    runtime: ['node'],
    summary: 'Node-only SFTP adapter candidate for a shared remote-filesystem GraphQL contract.',
    flow: ['SFTP', 'GraphQL', 'files'],
    example: 'query { remoteFiles(path: "/incoming") { name size } }',
  },
  {
    repo: 'graphql-api-slate-host',
    pkg: '@graphql-api/slate-host',
    status: 'audit',
    category: 'api',
    runtime: ['node'],
    summary:
      'Slate Host integration seed; verify the upstream service and schema value before migration.',
    flow: ['Slate Host', 'GraphQL', 'site'],
    example: 'query { hostedSite(id: "…") { id status } }',
  },
  {
    repo: 'graphql-api-openai-gpt3',
    pkg: null,
    status: 'audit',
    category: 'ai',
    runtime: ['node'],
    summary:
      'Historical GPT-3-era repository; any revival requires a current OpenAI API redesign rather than dependency bumps.',
    flow: ['model API', 'GraphQL', 'generation'],
    example: 'mutation { generate(input: { prompt: "hello" }) { id } }',
  },
  {
    repo: 'graphql-api.github.io',
    pkg: null,
    status: 'historical',
    category: 'site',
    runtime: ['browser'],
    summary: 'Historical Pages deployment repository; modern docs now live in the core workspace.',
    flow: ['docs build', 'Pages', 'browser'],
    example: 'query { docs { version url } }',
  },
  {
    repo: 'graphql-iso-ftp',
    pkg: '@graphql-api/ftp',
    status: 'migrate',
    category: 'filesystem',
    runtime: ['node'],
    summary:
      'FTP abstraction seed; retain only with explicit insecure-transport documentation and adapter boundaries.',
    flow: ['FTP', 'GraphQL', 'files'],
    example: 'query { remoteFiles(path: "/pub") { name size } }',
  },
  {
    repo: 'apollo-datasource-webdav',
    pkg: '@graphql-api/apollo-datasource-webdav',
    status: 'historical',
    category: 'filesystem',
    runtime: ['node'],
    summary:
      'Historical Apollo WebDAV datasource; extract protocol adapter behavior into the modern filesystem contract.',
    flow: ['WebDAV', 'GraphQL', 'files'],
    example: 'query { remoteFiles(path: "/dav") { name etag } }',
  },
  {
    repo: 'types',
    pkg: '@graphql-api/types',
    status: 'migrate',
    category: 'core',
    runtime: ['browser', 'node', 'edge', 'worker'],
    summary:
      'Existing type package seed; fold into the new shared protocol/capability/artifact contract.',
    flow: ['contracts', 'TypeScript', 'packages'],
    example: 'query { capabilities { name runtime } }',
  },
  {
    repo: 'graphql-iso-webdav',
    pkg: '@graphql-api/webdav',
    status: 'migrate',
    category: 'filesystem',
    runtime: ['node', 'browser'],
    summary: 'WebDAV abstraction seed for a provider-neutral remote-filesystem package.',
    flow: ['WebDAV', 'GraphQL', 'files'],
    example: 'mutation { writeRemoteFile(path: "/note.md", text: "hello") { etag } }',
  },
  {
    repo: 'graphql-api-plaid',
    pkg: '@graphql-api/template',
    status: 'repair',
    category: 'api',
    runtime: ['node'],
    summary:
      'Repository currently carries copied template package identity; repair metadata before any API audit or release.',
    flow: ['Plaid', 'GraphQL', 'finance'],
    example: 'query { accounts { id name } }',
  },
  {
    repo: 'next-apollo-handler',
    pkg: null,
    status: 'historical',
    category: 'runtime',
    runtime: ['node'],
    summary:
      'Historical Next/Apollo handler experiment; extract only reusable request/response semantics.',
    flow: ['Next request', 'GraphQL', 'response'],
    example: 'query { health { ok } }',
  },
  {
    repo: 'cloudflare-worker-apollo-handler',
    pkg: null,
    status: 'historical',
    category: 'runtime',
    runtime: ['worker'],
    summary:
      'Historical Cloudflare/Apollo handler; supersede with a modern Worker dispatch/transport adapter.',
    flow: ['Worker request', 'GraphQL', 'response'],
    example: 'mutation { dispatchWorker(input: { method: "health" }) { state } }',
  },
  {
    repo: 'branding',
    pkg: null,
    status: 'scaffold',
    category: 'site',
    runtime: ['browser'],
    summary:
      'Non-package branding repository; catalogued separately from supported integration packages.',
    flow: ['assets', 'docs', 'brand'],
    example: 'query { repository(name: "branding") { status } }',
  },
  {
    repo: 'graphql-api-obsidian',
    pkg: null,
    status: 'audit',
    category: 'api',
    runtime: ['browser', 'node'],
    summary:
      'Obsidian integration experiment; clarify plugin/local-file use case before defining a publishable schema.',
    flow: ['vault', 'GraphQL', 'notes'],
    example: 'query { notes(path: "/") { path title } }',
  },
  {
    repo: 'graphql-api-umami',
    pkg: '@graphql-api/template',
    status: 'repair',
    category: 'api',
    runtime: ['node', 'edge'],
    summary:
      'Umami repository has copied template metadata; repair identity, then validate current analytics API.',
    flow: ['Umami', 'GraphQL', 'analytics'],
    example: 'query { pageviews(range: "7d") { timestamp value } }',
  },
  {
    repo: 'graphql-api-stackblitz',
    pkg: '@graphql-api/stackblitz',
    status: 'reference',
    category: 'api',
    runtime: ['browser', 'node'],
    summary:
      'Second reference migration candidate with an existing build/test surface and StackBlitz SDK integration.',
    flow: ['project spec', 'GraphQL', 'StackBlitz'],
    example: 'mutation { openProject(input: { title: "demo" }) { url } }',
  },
  {
    repo: 'graphql-fs',
    pkg: '@graphql-api/template',
    status: 'repair',
    category: 'filesystem',
    runtime: ['browser', 'node'],
    summary:
      'Filesystem experiment with copied template metadata; repair identity and align with the shared filesystem/snapshot contract.',
    flow: ['filesystem', 'GraphQL', 'snapshot'],
    example: 'query { files(path: "/") { name kind } }',
  },
  {
    repo: 'graphql-local-cron',
    pkg: '@graphql-local/cron',
    status: 'reference',
    category: 'runtime',
    runtime: ['browser', 'node'],
    summary:
      'Best first migration reference: GraphQL 16, Rollup 4, Vitest and local cron/IDB behavior.',
    flow: ['cron expression', 'GraphQL', 'schedule'],
    example: 'mutation { schedule(cron: "0 * * * *") { id nextRun } }',
  },
]
