#  https://graphql-inspector.com/docs/products/action
name: CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
              schema: 'schema.graphql' # important to define a path to schema file, without a branch
              endpoint: 'https://my-app.com/graphql'
